### GET all contacts
GET https://project1-2qxs.onrender.com/contacts HTTP/1.1

### GET contact by ID
GET https://project1-2qxs.onrender.com/contacts/69b8872634a82e4dfac3dc1d HTTP/1.1

### CREATE contact
POST https://project1-2qxs.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Matias",
  "lastName": "Lopez",
  "email": "matiaslopez@test.com",
  "favoriteColor": "Blue",
  "birthday": "05/03/2001"
}


### DELETE contact
DELETE https://project1-2qxs.onrender.com/contacts/69b8872634a82e4dfac3dc1d HTTP/1.1

### PUT (Update) contact
PUT https://project1-2qxs.onrender.com/contacts/69bdd673e45df5465f2941ed HTTP/1.1
Content-Type: application/json

{
  "firstName": "Matias",
  "lastName": "Lopez",
  "email": "matiaslopez@test.com",
  "favoriteColor": "Black",
  "birthday": "05/03/2002"
}

